# Generated by Django 5.2.6 on 2026-04-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modulos_permitidos',
            field=models.ManyToManyField(blank=True, to='usuarios.modulo'),
        ),
    ]
