# Generated by Django 5.2.6 on 2026-04-08 23:20

from django.db import migrations

def crear_modulos(apps, schema_editor):
    Modulo = apps.get_model('usuarios', 'Modulo')
    modulos = [
        ('Información Operacional', 'ver_informacion_operacional'),
        ('Usuarios', 'ver_usuarios'),
        ('Clientes', 'ver_clientes'),
        ('Compras', 'ver_compras'),
        ('Empresa', 'ver_empresa'),
        ('Inventario', 'ver_inventario'),
        ('Caja', 'ver_caja'),
        ('Ventas', 'ver_ventas'),
    ]
    for nombre, codigo in modulos:
        Modulo.objects.get_or_create(codigo=codigo, defaults={'nombre': nombre})

def eliminar_modulos(apps, schema_editor):
    Modulo = apps.get_model('usuarios', 'Modulo')
    codigos = [c for _, c in modulos]
    Modulo.objects.filter(codigo__in=codigos).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_modulos_permitidos'),  # ← nombre REAL de la migración que agregó el campo ManyToMany
    ]

    operations = [
        migrations.RunPython(crear_modulos, eliminar_modulos),
    ]