# Generated by Django 5.2.6 on 2026-03-17 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_codigo_barras_codigobarras'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_cambio', models.CharField(choices=[('añadido', 'Añadido'), ('vendido', 'Vendido'), ('ajuste', 'Ajuste')], max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_stock', to='inventario.producto')),
            ],
        ),
    ]
