# Generated by Django 5.2.6 on 2026-05-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_historialstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigobarras',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
