# Generated by Django 5.2.6 on 2026-07-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_codigobarras_usado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='inventario__stock_0a3383_idx'),
        ),
    ]
