# Generated by Django 5.2.6 on 2026-03-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('mensaje_ticket', models.TextField(blank=True, help_text='Mensaje que aparecerá al final del ticket')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio de operaciones', null=True)),
            ],
        ),
    ]
