# Generated by Django 5.2.6 on 2026-03-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
