# Generated by Django 5.2.6 on 2026-03-31 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_caja_usuario_apertura_caja_usuario_cierre_and_more'),
        ('ventas', '0004_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.caja'),
        ),
    ]
