# Generated by Django 5.2.6 on 2026-07-28 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
        ('ventas', '0005_venta_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='rutas.ruta'),
        ),
    ]
