# Generated by Django 5.2.6 on 2026-07-28 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_cortecaja_caja_cortec_fecha_c_920cce_idx_and_more'),
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
        ('ventas', '0006_venta_ruta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='ventas_vent_fecha_8683f5_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['caja', 'fecha'], name='ventas_vent_caja_id_c36e8c_idx'),
        ),
    ]
