# Generated by Django 5.2.6 on 2026-03-31 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_caja_usuario_apertura_caja_usuario_cierre_and_more'),
        ('ventas', '0005_venta_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='ventas.venta'),
        ),
    ]
