# Generated by Django 5.2.6 on 2026-07-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_transaccion_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortecaja',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
