# Generated by Django 5.2.6 on 2026-07-28 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_cortecaja_fecha_fin_cortecaja_fecha_inicio'),
        ('ventas', '0006_venta_ruta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cortecaja',
            index=models.Index(fields=['fecha_corte'], name='caja_cortec_fecha_c_920cce_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha'], name='caja_transa_fecha_efc731_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['caja', 'fecha'], name='caja_transa_caja_id_02f41d_idx'),
        ),
    ]
