# Generated by Django 5.2.6 on 2026-07-28 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_cortecaja_caja_cortec_fecha_c_920cce_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cortecaja',
            options={'ordering': ['-fecha_corte']},
        ),
    ]
